fix(discord): use author instead of channel.recipient in get_chat_info
Fixes AttributeError: 'NoneType' object has no attribute 'name'

Signed-off-by: yshalsager <ysh-alsager@hotmail.com>